version: '3.8'
services:
   web:
       build: .
       command: sh -c "python manage.py makemigrations &&
                       python manage.py migrate &&
                       export DJANGO_SUPERUSER_PASSWORD=rodrigo &&
                       python manage.py createsuperuser --no-input --username=rodrigo --email rlocoselli@yahoo.com.br &&
                       python manage.py runserver 0:8000"
       ports:
           - 8000:8000